# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='Aaron', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='Chesley', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(default='Darrell', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='social_security_number',
            field=models.CharField(default=529990819, max_length=12),
            preserve_default=False,
        ),
    ]
